services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/crypto_spot_collector/apps/secrets.json:/app/crypto_spot_collector/apps/secrets.json:ro
      - ./logs:/app/crypto_spot_collector/apps/logs
    # command: sleep infinity
    command: uv run crypto_spot_collector/apps/buy_spot.py
    depends_on:
      - mysql
    networks:
      - crypto-network
    environment:
      - DATABASE_URL=mysql://crypto_user:crypto_pass@mysql:3306/crypto_pachinko

  app_perp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/crypto_spot_collector/apps/secrets.json:/app/crypto_spot_collector/apps/secrets.json:ro
      - ./logs:/app/crypto_spot_collector/apps/logs
    # command: sleep infinity
    command: uv run crypto_spot_collector/apps/buy_perp.py
    depends_on:
      - mysql
    networks:
      - crypto-network
    environment:
      - DATABASE_URL=mysql://crypto_user:crypto_pass@mysql:3306/crypto_pachinko

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/crypto_spot_collector/apps/secrets.json:/app/crypto_spot_collector/apps/secrets.json:ro
      - ./logs:/app/crypto_spot_collector/apps/logs
    # command: sleep infinity
    command: uv run crypto_spot_collector/apps/discord_appliation.py
    depends_on:
      - mysql
    networks:
      - crypto-network
    environment:
      - DATABASE_URL=mysql://crypto_user:crypto_pass@mysql:3306/crypto_pachinko

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crypto-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=crypto_pachinko
      - MYSQL_USER=crypto_user
      - MYSQL_PASSWORD=crypto_pass
    ports:
      - "3306:3306"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "9001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_LEVEL=debug # 表示するログレベル (debug, info, warn, error)

volumes:
  mysql-data:
  portainer_data:

networks:
  crypto-network:
    driver: bridge
