services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/crypto_spot_collector/apps/secrets.json:/app/crypto_spot_collector/apps/secrets.json:ro
      - ./logs:/app/crypto_spot_collector/scripts/logs
    # command: sleep infinity
    command: uv run crypto_spot_collector/apps/buy_spot.py
    depends_on:
      - mysql
    networks:
      - crypto-network
    environment:
      - DATABASE_URL=mysql://crypto_user:crypto_pass@mysql:3306/crypto_pachinko

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/crypto_spot_collector/apps/secrets.json:/app/crypto_spot_collector/apps/secrets.json:ro
      - ./logs:/app/crypto_spot_collector/scripts/logs
    # command: sleep infinity
    command: uv run crypto_spot_collector/apps/discord_appliation.py
    depends_on:
      - mysql
    networks:
      - crypto-network
    environment:
      - DATABASE_URL=mysql://crypto_user:crypto_pass@mysql:3306/crypto_pachinko

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crypto-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=crypto_pachinko
      - MYSQL_USER=crypto_user
      - MYSQL_PASSWORD=crypto_pass
    ports:
      - "3306:3306"

volumes:
  mysql-data:


networks:
  crypto-network:
    driver: bridge
